version: '3.11'

services:
  web:
    platform: linux/amd64
    image: rafacom/project_with_posts:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - "80:80"
    volumes:
      - /home/testuser/project_with_posts_docker_ci/uploads/images:/app/uploads/images
      - /home/testuser/project_with_posts_docker_ci/posts:/app/posts
    restart: always