version: '3.11'

services:
  web:
    platform: linux/amd64
    image: rafacom/project_with_posts
    build: .
    ports:
      - "80:80"
    volumes:
       - /Users/rafaelsirinan/Desktop/Python_projects/hosting_deployment/Docker/project_with_posts_docker/posts:/app/posts
       - /Users/rafaelsirinan/Desktop/Python_projects/hosting_deployment/Docker/project_with_posts_docker/uploads/images:/app/uploads/images
#      - /home/testuser/project_with_posts_docker_ci/uploads/images:/app/uploads/images
#      - /home/testuser/project_with_posts_docker_ci/posts:/app/posts
    restart: always

