name: Build and deploy workflow
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v3
      - name: docker build
        run: docker build -t rafacom/project_with_posts:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push rafacom/project_with_posts:$GITHUB_REF_NAME-$GITHUB_RUN_ID
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: clone code
        uses: actions/checkout@v3
      - name: render configs
        run: |
          mkdir deploy 
          cat docker-compose-ci.yaml | envsubst > deploy/docker-compose.yaml
#          cat Dockerfile | envsubst > deploy/Dockerfile
#          cat docker_ci_config.py | envsubst > deploy/docker_config.py
      - name: copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "deploy/docker-compose.yaml"
          target: "project_with_posts_docker_ci"
          strip_components: 1
      - name: deploy app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd project_with_posts_docker_ci
            echo ${{ secrets.PASSWORD }} | sudo -S docker-compose up -d
# Изменить HOST в секретах
# сервер запускается, осталось исправить то, что картинки не отображаются и не загружаются
# как я думаю, проблема в том, что пути в json файле не сходятся с путями на ВМ так как там пришлось создавать доп директории и тд
# остальные картинки грузяться так как они подгружаются из инета